export interface Dons {
    idDons?: number; // Optional since it's generated by the backend
    nomDoneur: string;
    prenomDoneur: string;
    quantite: number;
    donationDate?: Date; // Optional, will be set by the backend
    idDonation: number; // The ID of the donation being contributed to
    subscriberId?: number; // Optional if the donor is a registered subscriber
}
