export enum TypeEvent {
    ANIMAL_WELFARE='ANIMAL_WELFARE',
    EDUCATIONAL_WORKSHOP='EDUCATIONAL_WORKSHOP',
    VOLUNTEERING_CAMPAIGN='VOLUNTEERING_CAMPAIGN',
    MEDICAL='MEDICAL',
    COMMUNITY_AWARENESS='COMMUNITY_AWARENESS'
}

export const EventArray = Object.values(TypeEvent);
